name: poms
description: "POMS - Post-Operative Monitoring System Mobile App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^15.1.2

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Network
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

  # Local storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

  # Utilities
  intl: ^0.20.2
  equatable: ^2.0.7

  # UI
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.1

  # App version check
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.4
  json_serializable: ^6.9.5
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  husky: ^0.1.7
  lint_staged: ^0.5.1

flutter:
  uses-material-design: true

lint_staged:
  "lib/**.dart":
    - fvm dart format
    - fvm dart fix --apply
    - git add
    - fvm flutter analyze
